name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install security tools
      run: pip install bandit safety

    - name: Run Bandit (Skanowanie kodu)
      # Ignorujemy folder z testami i środowisko wirtualne, skanujemy resztę
      run: bandit -r . -x ./venv,./tests

    - name: Run Safety (Skan zależności)
      run: safety check -r requirements.txt
